version: "3"

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_DASHBOARDS_MIN_REFRESH_INTERVAL=100ms"
      - "GF_PANELS_DISABLE_SANITIZE_HTML=true"
    volumes:
      - "./grafana_datasources.yaml:/etc/grafana/provisioning/datasources/prometheus_docker-compose.yaml"
      - grafana-storage:/var/lib/grafana
      - "./grafana-images/:/usr/share/grafana/public/img/"
    restart: always

volumes:
  grafana-storage: {}
  graphite-storage: {}
