extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  carbon:
    endpoint: 'graphite:2003'
    # by default it will export to localhost:2003 using tcp
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  #carbon:
  #carbon exporter supports carbon's plaintext protocol
  #default endpoint localhost:2003 and timeout: 5s
    #endpoint: ':2003'
    #timeout: 5s

  prometheus:
    endpoint: ':9464'
    # namespace: test-space
    # const_labels:
    #   label1: value1
    metric_expiration: 600m
    send_timestamps: true
    # add_metric_suffixes: false
    # enable_open_metrics: true
    # resource_to_telemetry_conversion:
    #   enabled: true

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      #processors: [batch]
      exporters: [prometheus,carbon]