extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

connectors:
  spanmetrics:
    namespace: span.metrics

exporters:
  prometheus:
    endpoint: ':9464'
    # namespace: test-space
    # const_labels:
    #   label1: value1
    metric_expiration: 600m
    send_timestamps: true
    # add_metric_suffixes: false
    # enable_open_metrics: true
    # resource_to_telemetry_conversion:
    #   enabled: true

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      #processors: [batch]
      exporters: [prometheus]