global:
  scrape_interval:     1s # By default, scrape targets every 10 seconds.

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'app'
    scrape_interval: 40ms
    static_configs:
      - targets: ["host.docker.internal:8000"]
  - job_name: 'default'
    static_configs:
      - targets: ['localhost:9090']